version: "3.8"

services:

  tts_app:
    image: "${APP_IMAGE}"
    build:
      context: .  # Root directory (where this file is)
      dockerfile: timetable_solutions/Dockerfile  # Dockerfile specifies the build for the app, and is also at project root
      cache_from:
        - "${APP_IMAGE}"
    volumes:
      - static_volume:/timetable_scheduling/static  # mirror static COLLECTION in container
      - media_volume:/timetable_scheduling/media  # mirror media COLLECTION in container
    expose:
      - 8000

  tts_nginx:
    image: "${NGINX_IMAGE}"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: tts_nginx_c
    ports:
      - 80:80
    volumes:
      - static_volume:/var/www/timetable_scheduling/staticfiles  # Mirror the static files into relevant part of nginx
      - media_volume:/var/www/timetable_scheduling/mediafiles
    depends_on:
      - tts_app

volumes:
  static_volume:  # static_volume acts like a pivot between static files in the tts_app and nginx containers
  media_volume:  # Similarly for media_volume
