# Generated by Django 4.0.6 on 2022-08-15 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.IntegerField()),
                ('building', models.CharField(max_length=20)),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FixedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20)),
                ('subject_name', models.CharField(choices=[('MATHS', '#b3f2b3'), ('ENGLISH', '#ffbfd6'), ('FRENCH', '#c8d4e3'), ('LUNCH', '#b3b3b3'), ('FREE', '#feffba')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('year_group', models.IntegerField(choices=[(1, '#b3f2b3'), (2, '#ffbfd6'), (3, '#c8d4e3'), (4, '#fcc4a2'), (5, '#babac2')])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField()),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=9)),
                ('period_start_time', models.TimeField(choices=[(datetime.time(9, 0), 'PERIOD_ONE'), (datetime.time(10, 0), 'PERIOD_TWO'), (datetime.time(11, 0), 'PERIOD_THREE'), (datetime.time(12, 0), 'PERIOD_FOUR'), (datetime.time(13, 0), 'LUNCH'), (datetime.time(14, 0), 'PERIOD_FIVE'), (datetime.time(15, 0), 'PERIOD_SIX')])),
                ('period_duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
            ],
        ),
    ]
