# Generated by Django 4.0.6 on 2022-07-23 07:18
"""Data migration for autopopulating some default data in the timetable database."""

# Standard library imports
import datetime as dt

# Django imports
from django.db import migrations

# Local application imports
from ..models import TimetableSlot


def add_default_timetable_structure(apps, schema_editor):
    """
    Function for populating the database with a default timetable structure.

    apps: app registry that has the historical versions of all models loaded into it, to match where
    the migrations sits
    schema_editor: the SchemaEditor, which is used to manually effect database schema changes.
    """
    default_slots = [TimetableSlot(day_of_week=day, period_start_time=time, period_duration=dt.timedelta(hours=1)) for
                     time in TimetableSlot.PeriodStart.values for day in TimetableSlot.WeekDay.values]
    for slot in default_slots:
        slot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_selector', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_timetable_structure)
    ]
