# Generated by Django 4.0.6 on 2022-08-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable_selector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsolvedClass',
            fields=[
                ('class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(choices=[('#b3f2b3', 'Maths'), ('#ffbfd6', 'English'), ('#c8d4e3', 'French'), ('#b3b3b3', 'Lunch'), ('#feffba', 'Free')], max_length=20)),
                ('teaching_hours', models.DurationField()),
                ('min_slots', models.PositiveSmallIntegerField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsolved_classes', to='timetable_selector.classroom')),
                ('pupils', models.ManyToManyField(related_name='unsolved_classes', to='timetable_selector.pupil')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsolved_classes', to='timetable_selector.teacher')),
            ],
        ),
    ]
