# Generated by Django 4.0.6 on 2022-08-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable_selector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsolvedClass',
            fields=[
                ('class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(choices=[('MATHS', '#b3f2b3'), ('ENGLISH', '#ffbfd6'), ('FRENCH', '#c8d4e3'), ('LUNCH', '#b3b3b3'), ('FREE', '#feffba')], max_length=20)),
                ('total_slots', models.PositiveSmallIntegerField()),
                ('min_slots', models.PositiveSmallIntegerField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsolved_classes', to='timetable_selector.classroom')),
                ('pupils', models.ManyToManyField(related_name='unsolved_classes', to='timetable_selector.pupil')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsolved_classes', to='timetable_selector.teacher')),
            ],
        ),
    ]
