# Generated by Django 4.0.6 on 2022-08-15 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable_requirements', '0001_initial'),
        ('timetable_selector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsolvedclass',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsolved_classes', to='timetable_selector.classroom'),
        ),
        migrations.AddField(
            model_name='unsolvedclass',
            name='pupils',
            field=models.ManyToManyField(related_name='unsolved_classes', to='timetable_selector.pupil'),
        ),
    ]
