# Generated by Django 4.0.6 on 2022-08-15 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable_requirements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable_selector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsolvedclass',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unsolvedclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsolved_classes', to='timetable_selector.teacher'),
        ),
    ]
