# Generated by Django 4.1.2 on 2022-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Teacher'), (3, 'Pupil')], default=1),
        ),
    ]
