# Generated by Django 4.1.7 on 2023-03-07 19:23

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_teacher_unique_constraint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="yeargroup",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="yeargroup",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("year_group_id"),
                name="year_group_id_unique_for_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="yeargroup",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("year_group_name"),
                name="year_group_name_unique_for_school",
            ),
        ),
    ]
