# Generated by Django 4.1.2 on 2023-01-06 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_yeargroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pupil",
            options={"ordering": ["surname", "firstname"]},
        ),
        migrations.AlterModelOptions(
            name="yeargroup",
            options={"ordering": ["year_group"]},
        ),
        migrations.AlterField(
            model_name="pupil",
            name="year_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pupils",
                to="data.yeargroup",
            ),
        ),
    ]
