# Generated by Django 4.1.7 on 2023-03-07 19:28

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_alter_yeargroup_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("classroom_id"),
                name="classroom_id_unique_for_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("building"),
                models.F("room_number"),
                name="classroom_building_room_number_unique_for_school",
            ),
        ),
    ]
