# Generated by Django 4.1.7 on 2023-03-07 19:31

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_classroom_classroom_id_unique_for_school_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pupil",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="pupil",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("pupil_id"),
                name="pupil_id_unique_for_school",
            ),
        ),
    ]
