# Generated by Django 4.1.7 on 2023-03-07 19:39

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_alter_pupil_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="break",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("break_id"),
                name="break_id_unique_for_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="break",
            constraint=models.CheckConstraint(
                check=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="break_ends_after_it_starts",
            ),
        ),
    ]
