# Generated by Django 4.1.7 on 2023-03-08 07:02

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_break_break_id_unique_for_school_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timetableslot",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("slot_id"),
                name="slot_id_unique_for_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableslot",
            constraint=models.CheckConstraint(
                check=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="slot_ends_after_it_starts",
            ),
        ),
    ]
