# Generated by Django 4.1.7 on 2023-03-08 08:02

# Django imports
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_timetableslot_slot_id_unique_for_school_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                models.F("school"),
                models.F("lesson_id"),
                name="lesson_id_unique_for_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "total_required_slots__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_required_double_periods"),
                            "*",
                            models.Value(2),
                        ),
                    )
                ),
                name="number_of_double_period_slots_cannot_exceed_total_required_slots",
            ),
        ),
    ]
