# Generated by Django 4.1.7 on 2023-03-10 07:13

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_alter_lesson_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="break",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="timetableslot",
            unique_together=set(),
        ),
    ]
