name: Continuous delivery to production

on: [push]

env:
  WEB_IMAGE: gchr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/web
  NGINX_IMAGE: gchr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/nginx

jobs:

  build:
    name: Build Docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo DEBUG=0 >> .env
          echo SQL_ENGINE=django.db.backends.postgresql >> .env
          echo DATABASE=postgres >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo SQL_DATABASE=${{ secrets.POSTGRES_NAME }} >> .env
          echo SQL_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo SQL_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo SQL_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo SQL_PORT=${{ secrets.POSTGRES_PORT }} >> .env
      - name: Set environment variables
        run: |
          echo "WEB_IMAGE=$(echo ${{env.WEB_IMAGE}} )" >> $GITHUB_ENV
          echo "NGINX_IMAGE=$(echo ${{env.NGINX_IMAGE}} )" >> $GITHUB_ENV
      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Pull docker images
        run: |
          docker pull ${{ env.WEB_IMAGE }} || true
          docker pull ${{ env.NGINX_IMAGE }} || true
      - name: Build docker images
        run: |
          docker-compose -f docker-compose.cd.yml build
      - name: Push docker images
        run: |
          docker push ${{ env.WEB_IMAGE }}
          docker push ${{ env.NGINX_IMAGE }}
