name: CI testing

on:
  # Every push (notably the push resulting from a successful merge to main) will run the test suite
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install project dependencies
      run: |
        pip install -r timetable_solutions/app-requirements.txt
        pip install -r timetable_solutions/test-requirements.txt
    - name: Run test suite with pytest
      run: |
        cd timetable_solutions
        pytest
