name: Continuous integration

on:
  # Pull requests, pushes to main, or manual execution can all run the test suite
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install project dependencies
      run: |
        pip install -r timetable_solutions/app-requirements.txt
        pip install -r timetable_solutions/dev-requirements.txt
    - name: Run test suite with pytest
      run: |
        cd timetable_solutions
        pytest

  mypy-type-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install project dependencies
      run: |
        pip install mypy==0.991
    - name: Run mypy in project layers
      run: |
        cd timetable_solutions
        mypy -p domain --ignore-missing-imports --disallow-untyped-defs
