name: Continuous integration

on:
  # Pull requests, pushes to main, or manual execution can all run the test suite
  push:
    branches: ['main', '62-diff-tts-for-year-groups']
  pull_request:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install project dependencies
      run: |
        pip install -r timetable_solutions/app-requirements.txt
        pip install -r timetable_solutions/test-requirements.txt
    - name: Run test suite with pytest
      run: |
        cd timetable_solutions
        pytest --cov=. --cov-config=pytest.ini

  mypy-type-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install mypy
      run: |
        pip install mypy==1.0.1
    - name: Run mypy in project layers
      run: |
        cd timetable_solutions
        mypy -p data
        mypy -p domain
        mypy -p interfaces

  black-code-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install black
      run: |
        pip install black==23.1.0
    - name: Run black on all python code
      run: |
        cd timetable_solutions
        black .

  isort-import-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install isort
      run: |
        pip install isort==5.12.0
    - name: Run isort on all python code
      run: |
        cd timetable_solutions
        isort . --profile=black
